function m(b,a,c,d,e){b.j.qb(b.tb,a,c,d,e)}function n(b,a,c,d){b.j.ea?m(b,a,c,d):b.j.Ze()._OnMessageFromDOM({type:"event",component:b.tb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function q(b,a,c){b.j.B(b.tb,a,c)}function v(b,a){for(const [c,d]of a)q(b,c,d)}function w(b){b.Yb||(b.j.Fc(b.oe),b.Yb=!0)}function aa(b){b.Yb&&(b.j.Nd(b.oe),b.Yb=!1)}window.kb=class{constructor(b,a){this.j=b;this.tb=a;this.Yb=!1;this.oe=()=>this.Ia()}wd(){}Ia(){}};
window.Lf=class{constructor(){this.rd=-1}l(){-1!==this.rd&&(self.clearTimeout(this.rd),this.rd=-1)}};"use strict";class ba{constructor(b){this.Wa=b;this.Xc=!1;this.ed=!0;this.xb=this.sa=this.sd=-1}}
function ca(b,a){const c=a.elementId,d=b.Ad(c,a),e=new ba(d);b.za.set(c,e);d.style.boxSizing="border-box";d.style.display="none";e.ed=!!a.isVisible;d.addEventListener("focus",()=>{x(b,"elem-focused",c)});d.addEventListener("blur",()=>{x(b,"elem-blurred",c)});const f=a.htmlIndex;e.sd=f;e.xb=a.htmlZIndex;b.Ma&&(a=b.j.wc(f),e.sa=a,b.j.Nb(a).appendChild(d))}function y(b,a,c){q(b,a,d=>{const e=z(b,d.elementId);return c(e,d)})}
function z(b,a){b=b.za.get(a);if(!b)throw Error(`no element with id ${a}`);return b.Wa}function x(b,a,c,d){d||(d={});d.elementId=c;m(b,a,d)}
window.vc=class extends self.kb{constructor(b){super(b,"video");this.za=new Map;this.Ma=!0;v(this,[["create",a=>ca(this,a)],["destroy",a=>{a=a.elementId;const c=z(this,a);this.Cd(c);this.Ma&&c.parentElement.removeChild(c);this.za.delete(a)}],["set-visible",a=>{if(this.Ma){var c=this.za.get(a.elementId),d=c.Wa;c.Xc?d.style.display=a.isVisible?"":"none":c.ed=!!a.isVisible}}],["update-position",a=>{if(this.Ma){var c=this.za.get(a.elementId),d=c.Wa,e=this.j;d.style.left=a.left+"px";d.style.top=a.top+
"px";d.style.width=a.width+"px";d.style.height=a.height+"px";var f=a.fontSize;null!==f&&(d.style.fontSize=f+"em");f=a.htmlIndex;c.sd=f;f=e.wc(f);f!==c.sa&&(d.remove(),e.Nb(f).appendChild(d),c.sa=f,e.Qc());a=a.htmlZIndex;a!==c.xb&&(c.xb=a,e.Qc());c.Xc||(c.Xc=!0,c.ed&&(d.style.display=""))}}],["update-state",a=>{z(this,a.elementId);this.Gd()}],["focus",a=>this.Nc(a)],["set-css-style",a=>{const c=z(this,a.elementId),d=a.prop;a=a.val;d.startsWith("--")?c.style.setProperty(d,a):c.style[d]=a}],["set-attribute",
a=>{z(this,a.elementId).setAttribute(a.name,a.val)}],["remove-attribute",a=>{z(this,a.elementId).removeAttribute(a.name)}]]);y(this,"get-element",a=>a)}Ad(){throw Error("required override");}Cd(){}Gd(){throw Error("required override");}Nc(b){var a=z(this,b.elementId);b.focus?a.focus():a.blur()}};"use strict";const da=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),A=/android/i.test(navigator.userAgent);let ea=0;
function B(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.Bf?new Promise(c=>{const d="c3_resolve_"+ea;++ea;self[d]=c;a.textContent=b.Ff+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}
async function fa(){if(!navigator.userActivation||"undefined"===typeof OffscreenCanvas)return!1;try{let b=!1;const a=new Worker(URL.createObjectURL(new Blob(['\n\tself.addEventListener("message", () =>\n\t{\n\t\ttry {\n\t\t\tconst offscreenCanvas = new OffscreenCanvas(32, 32);\n\t\t\tconst gl = offscreenCanvas.getContext("webgl");\n\t\t\tself.postMessage(!!gl);\n\t\t}\n\t\tcatch (err)\n\t\t{\n\t\t\tconsole.warn("Feature detection worker error:", err);\n\t\t\tself.postMessage(false);\n\t\t}\n\t});'],{type:"text/javascript"})),
{get type(){b=!0}}),c=await new Promise(d=>{a.addEventListener("message",e=>{a.terminate();d(e.data)});a.postMessage("")});return b&&c}catch(b){return console.warn("Error feature detecting worker mode: ",b),!1}}let D=new Audio;
const ha={"audio/webm; codecs=opus":!!D.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!D.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!D.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!D.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!D.canPlayType("audio/mp4"),"audio/mpeg":!!D.canPlayType("audio/mpeg")};D=null;async function ia(b){b=await ja(b);return(new TextDecoder("utf-8")).decode(b)}
function ja(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const ka=[];let F=0;window.RealFile=window.File;const G=[],la=new Map,ma=new Map;let na=0;const oa=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");oa.push(b)};const ra=new Set(["cordova","playable-ad","instant-games"]);let sa=!1;
window.ya=class b{constructor(a){this.ea=a.Hf;this.Ca=null;this.aa="";this.eb=a.Ef;this.Lb={};this.Ya=this.xa=null;this.Va=[];this.oa=null;this.be=!0;this.M=[];this.ld=[];this.md=!1;this.pe=()=>this.Xe();this.ad=!1;this.Wd=0;this.zb=null;this.cb=-1;this.wf=()=>this.hf();this.Ib=new Set;this.td=null;this.qe=[];this.u=a.re;this.Zb="file"===location.protocol.substr(0,4);if("playable-ad"===this.u||"instant-games"===this.u)this.ea=!1;if("cordova"===this.u&&this.ea&&A){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);
c&&90<=parseInt(c[1],10)||(this.ea=!1)}this.qa()?self.chrome.webview.addEventListener("message",c=>this.Md(c.data)):"macos-wkwebview"===this.u&&(self.C3WrapperOnMessage=c=>this.Md(c));this.bc=this.ua=null;"html5"!==this.u||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.B("canvas","update-size",c=>this.mf(c));this.B("canvas","set-html-layer-count",
c=>this._OnSetHTMLLayerCount(c));this.B("canvas","cleanup-html-layers",()=>this.cf());this.B("runtime","cordova-fetch-local-file",c=>this.df(c));this.B("runtime","create-job-worker",()=>this.ef());this.B("runtime","send-wrapper-extension-message",c=>this.lf(c));"cordova"===this.u?document.addEventListener("deviceready",()=>this.Kd(a)):this.Kd(a)}l(){this.Gc();this.Ca&&(this.Ca=this.Ca.onmessage=null);this.xa&&(this.xa.terminate(),this.xa=null);this.Ya&&(this.Ya.l(),this.Ya=null);for(const {canvas:a,
hb:c}of this.M)a.remove(),c.remove();this.M.length=0}Je(){return this.M[0].canvas}wc(a){return Math.min(a,this.M.length-1)}Nb(a){if(0>a||a>=this.M.length)throw new RangeError("invalid canvas layer");return this.M[a].hb}Ne(){return da&&"cordova"===this.u}ob(){const a=navigator.userAgent;return da&&ra.has(this.u)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}Le(){return A}Bc(){return A&&ra.has(this.u)}Ed(){return"windows-webview2"===this.u||!!("preview"===this.u&&window.chrome&&window.chrome.webview&&
window.chrome.webview.postMessage)}qa(){return this.Ed()||"xbox-uwp-webview2"===this.u}async Kd(a){this.ea&&!await fa()&&(this.ea=!1);"macos-wkwebview"===this.u?this.Ja({type:"ready"}):this.qa()&&(this.pf(),this.qe=(await this.bf()).registeredComponentIds);if("playable-ad"===this.u){this.ua=self.c3_base64files;this.bc={};await this.Ue();for(let d=0,e=a.gb.length;d<e;++d){var c=a.gb[d];this.bc.hasOwnProperty(c)?a.gb[d]={Bf:!0,Ff:this.bc[c]}:this.ua.hasOwnProperty(c)&&(a.gb[d]=URL.createObjectURL(this.ua[c]))}a.sc=
[]}if("nwjs"===this.u&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.Fc(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.Df?this.aa=a.Df:(c=location.origin,this.aa=("null"===c?"file:///":c)+location.pathname,c=this.aa.lastIndexOf("/"),-1!==c&&(this.aa=this.aa.substr(0,c+1)));a.Jf&&(this.Lb=a.Jf);c=new MessageChannel;this.Ca=c.port1;this.Ca.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.gf(d));this.zb=
new self.Oe(this);await ta(this.zb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.ea?await this.af(a,c.port2):await this.$e(a,c.port2)}Ic(a){a=this.Lb.hasOwnProperty(a)?this.Lb[a]:a.endsWith("/workermain.js")&&this.Lb.hasOwnProperty("workermain.js")?this.Lb["workermain.js"]:"playable-ad"===
this.u&&this.ua.hasOwnProperty(a)?this.ua[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async uc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.u&&this.Zb)return a=await this.Mb(d.Af?a:this.eb+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,
d)}ra(){return Math.max(window.innerWidth,1)}ia(){return Math.max(window.innerHeight,1)}Jd(a){var c=this.aa,d=location.href,e=this.ra(),f=this.ia(),g=window.devicePixelRatio,h=b.nb(),k=a.Pf,l=window.cr_previewImageBlobs||this.ua,p=window.cr_previewProjectFileBlobs,r=window.cr_previewProjectFiles,t=window.cr_swClientId||"";a=a.re;var u=(new URLSearchParams(self.location.search)).has("debug"),C=this.zb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,
projectData:k,previewImageBlobs:l,previewProjectFileBlobs:p,previewProjectFileSWUrls:r,swClientId:t,exportType:a,isDebug:u,ife:!!self.Of,jobScheduler:{inputPort:C.$c,outputPort:C.kd,maxNumWorkers:C.tf},supportedAudioFormats:ha,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.eb+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.eb+"opus.wasm.wasm",isFileProtocol:this.Zb,isiOSCordova:this.Ne(),isiOSWebView:this.ob(),isWindowsWebView2:this.Ed(),isAnyWebView2Wrapper:this.qa(),wrapperComponentIds:this.qe,
isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async af(a,c){const d=this.Ic(a.If);"preview"===this.u?(this.xa=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((l,p)=>{const r=t=>{this.xa.removeEventListener("message",r);t.data&&"ok"===t.data.type?l():p()};this.xa.addEventListener("message",r);this.xa.postMessage({type:"construct-worker-init","import":(new URL(d,this.aa)).toString()})})):this.xa=await this.uc(d,this.aa,{type:"module",name:"Runtime",Af:!0});
const e=document.createElement("canvas");e.style.display="none";const f=e.transferControlToOffscreen();document.body.appendChild(e);const g=document.createElement("div");g.className="c3htmlwrap";document.body.appendChild(g);this.M.push({canvas:e,hb:g});window.c3canvas=e;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let h=a.sc||[],k=a.gb;h=await Promise.all(h.map(l=>this.Sa(l)));k=await Promise.all(k.map(l=>this.Sa(l)));if("cordova"===this.u)for(let l=0,p=a.rc.length;l<p;++l){const r=
a.rc[l],t=r[0];if(t===a.ud||"scriptsInEvents.js"===t||t.endsWith("/scriptsInEvents.js"))r[1]=await this.Sa(t)}this.xa.postMessage(Object.assign(this.Jd(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:f,workerDependencyScripts:h,engineScripts:k,projectScripts:a.rc,mainProjectScript:a.ud,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,f,...ua(this.zb)]);this.Va=G.map(l=>new l(this));this.Id();va(e);wa(g);xa(this.oa);self.c3_callFunction=(l,p)=>{var r=this.oa;return r.j.Fd(r.tb,"js-invoke-function",
{name:l,params:p})};"preview"===this.u&&(self.goToLastErrorScript=()=>this.qb("runtime","go-to-last-error-script"))}async $e(a,c){const d=document.createElement("canvas");d.style.display="none";document.body.appendChild(d);var e=document.createElement("div");e.className="c3htmlwrap";document.body.appendChild(e);this.M.push({canvas:d,hb:e});window.c3canvas=d;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Va=G.map(h=>new h(this));this.Id();va(d);wa(e);e=a.gb.map(h=>"string"===
typeof h?(new URL(h,this.aa)).toString():h);if(Array.isArray(a.sc)){var f=[...a.sc].map(h=>h instanceof Blob?URL.createObjectURL(h):h);e.unshift(...f)}e=await Promise.all(e.map(h=>this.Sa(h)));await Promise.all(e.map(h=>B(h)));e=self.C3_ProjectScriptsStatus;f=a.ud;const g=a.rc;for(let [h,k]of g)if(k||(k=h),h===f)try{k=await this.Sa(k),await B(k),"preview"!==this.u||e[h]||this.Od(h,"main script did not run to completion")}catch(l){this.Od(h,l)}else if("scriptsInEvents.js"===h||h.endsWith("/scriptsInEvents.js"))k=
await this.Sa(k),await B(k);"preview"===this.u&&"object"!==typeof self.Kf.Mf?(this.Sb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Jd(a),{isInWorker:!1,messagePort:c,canvas:d,runOnStartupFunctions:oa}),xa(this.oa),this.Ld(),this.Ya=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Ya,
a))}Od(a,c){this.Sb();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Ld(){this.Sb()}Sb(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async ef(){const a=await za(this.zb);return{outputPort:a,transferables:[a]}}mf(a){if(!this.ad){var c=a.styleWidth+"px",d=a.styleHeight+
"px",e=a.marginLeft+"px",f=a.marginTop+"px";for(const {canvas:g,hb:h}of this.M)g.style.width=c,g.style.height=d,g.style.marginLeft=e,g.style.marginTop=f,h.style.width=c,h.style.height=d,h.style.marginLeft=e,h.style.marginTop=f,this.be&&(g.style.display="",h.style.display="");document.documentElement.style.setProperty("--construct-scale",a.displayScale);this.be=!1}}_OnSetHTMLLayerCount(a){var c=a.count,d=a.immediate,e=a.styleWidth+"px",f=a.styleHeight+"px";const g=a.marginLeft+"px",h=a.marginTop+"px";
a=[];const k=[];if(c<this.M.length)for(;this.M.length>c;){const {canvas:l,hb:p}=this.M.pop();p.remove();this.ea&&!d?this.ld.push(l):l.remove()}else if(c>this.M.length)for(let l=0,p=c-this.M.length;l<p;++l)c=document.createElement("canvas"),c.classList.add("c3overlay"),this.ea?(d=c.transferControlToOffscreen(),a.push(d),k.push(d)):a.push(c),document.body.appendChild(c),d=document.createElement("div"),d.classList.add("c3htmlwrap","c3overlay"),document.body.appendChild(d),c.style.width=e,c.style.height=
f,c.style.marginLeft=g,c.style.marginTop=h,d.style.width=e,d.style.height=f,d.style.marginLeft=g,d.style.marginTop=h,va(c),wa(d),this.M.push({canvas:c,hb:d});for(const l of this.Va)if(l instanceof window.vc&&l.Ma)for(const p of l.za.values())e=l.j.wc(p.sd),f=p.sa,-1!==e&&-1!==f&&e!==f&&(f=p.Wa,f.remove(),l.j.Nb(e).appendChild(f),p.sa=e);this.Qc();return{addedCanvases:a,transferables:k}}cf(){for(const a of this.ld)a.remove();this.ld.length=0}Qc(){this.md||(this.md=!0,this.Fc(this.pe))}Xe(){this.Nd(this.pe);
this.md=!1;let a=[];for(var c of this.Va)if(c instanceof window.vc){var d=c.Ma?[...c.za.values()]:null;d&&a.push(...d)}a.sort((g,h)=>{const k=g.sa,l=h.sa;return k!==l?k-l:g.xb-h.xb});let e=d=c=0,f=a.length;for(;e<f;++e){const g=a[e];g.sa!==c&&(this.Hd(c,a.slice(d,e)),c=g.sa,d=e)}d<e&&this.Hd(c,a.slice(d,e))}Hd(a,c){if(!(1>=c.length||a>=this.M.length)){c=c.map(k=>k.Wa);var d=new Set(c);a=this.Nb(a);for(var e=Array.from(a.children).filter(k=>d.has(k)),f=0,g=Math.min(c.length,e.length);f<g&&c[f]===e[f];++f);
for(var h=f;h<g;++h)e[h].remove();for(h=f;h<g;++h)a.appendChild(c[h])}}Ze(){if(this.ea)throw Error("not available in worker mode");return this.Ya}qb(a,c,d,e,f){this.Ca.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}Fd(a,c,d,e,f){const g=na++,h=new Promise((k,l)=>{ma.set(g,{resolve:k,reject:l})});this.Ca.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===
c)return this.ff(a);if("result"===c)this.jf(a);else if("runtime-ready"===c)this.kf();else if("alert-error"===c)this.Sb(),alert(a.message);else if("creating-runtime"===c)this.Ld();else throw Error(`unknown message '${c}'`);}ff(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=la.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Rb(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Rb(f,!0,h)).catch(h=>
{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Rb(f,!1,""+h)}):this.Rb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Rb(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.Ca.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}jf(a){const c=a.responseId,d=a.isOk;a=a.result;const e=ma.get(c);d?e.resolve(a):e.reject(a);ma.delete(c)}B(a,c,d){let e=la.get(a);e||(e=new Map,la.set(a,
e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static ib(a){if(G.includes(a))throw Error("DOM handler already added");G.push(a)}Id(){for(const a of this.Va)if("runtime"===a.tb){this.oa=a;return}throw Error("cannot find runtime DOM handler");}gf(a){this.qb("debugger","message",a)}kf(){for(const a of this.Va)a.wd()}static nb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||sa)}static Tb(a){sa=!!a}Fc(a){this.Ib.add(a);
this.Pc()}Nd(a){this.Ib.delete(a);0===this.Ib.size&&this.Gc()}Pc(){-1===this.cb&&0<this.Ib.size&&(this.cb=requestAnimationFrame(this.wf))}Gc(){-1!==this.cb&&(cancelAnimationFrame(this.cb),this.cb=-1)}hf(){this.cb=-1;for(const a of this.Ib)a();this.Pc()}ba(a){this.oa.ba(a)}ha(a){this.oa.ha(a)}Oc(){this.oa.Oc()}Qb(a){this.oa.Qb(a)}Me(){return!!ha["audio/webm; codecs=opus"]}async qf(a){a=await this.Fd("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}Qe(a){this.ad=!0;this.Wd=
a}Ke(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}Dd(a){return!this.Ke(a)}async Sa(a){return"cordova"===this.u&&(a.startsWith("file:")||this.Zb&&this.Dd(a))?(a.startsWith(this.aa)&&(a=a.substr(this.aa.length)),a=await this.Mb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async df(a){const c=a.filename;switch(a.as){case "text":return await this.Ie(c);case "buffer":return await this.Mb(c);default:throw Error("unsupported type");
}}zd(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async Ie(a){a=await this.zd(a);return await ia(a)}Hc(){if(ka.length&&!(8<=F)){F++;var a=ka.shift();this.Ve(a.filename,a.Gf,a.zf)}}Mb(a){return new Promise((c,d)=>{ka.push({filename:a,Gf:e=>{F--;this.Hc();c(e)},zf:e=>{F--;this.Hc();d(e)}});this.Hc()})}async Ve(a,c,d){try{const e=await this.zd(a),f=await ja(e);c(f)}catch(e){d(e)}}Md(a){if("entered-fullscreen"===
a)b.Tb(!0),H(this.oa);else if("exited-fullscreen"===a)b.Tb(!1),H(this.oa);else if("object"===typeof a){const c=a.type;"wrapper-init-response"===c?(this.td(a),this.td=null):"extension-message"===c?this.qb("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}lf(a){this.Ja({type:"extension-message",componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}Ja(a){this.qa()?window.chrome.webview.postMessage(JSON.stringify(a)):
"macos-wkwebview"===this.u&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}pf(){window.moveTo=(a,c)=>{this.Ja({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};window.resizeTo=(a,c)=>{this.Ja({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}bf(){return this.qa()?new Promise(a=>{this.td=a;this.Ja({type:"wrapper-init"})}):Promise.resolve()}async Ue(){const a=[];for(const [c,d]of Object.entries(this.ua))a.push(this.Te(c,d));
await Promise.all(a)}async Te(a,c){if("object"===typeof c)this.ua[a]=new Blob([c.str],{type:c.type}),this.bc[a]=c.str;else{let d=await this.Ye(c);d||(d=this.We(c));this.ua[a]=d}}async Ye(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}We(a){a=this.nf(a);return this.Se(a.data,
a.Cf)}nf(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{Cf:a,data:d}}Se(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],
{type:c})}};"use strict";const I=self.ya,Aa=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),J={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},Ba={dispatchUserScriptEvent:!0},Ca={dispatchRuntimeEvent:!0};function Da(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function Ea(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}
async function K(b){b=URL.createObjectURL(b);try{return await Ea(b)}finally{URL.revokeObjectURL(b)}}function Fa(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Ga(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await K(b);var d=await Fa(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await K(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await K(b)}
function Ha(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ia=new Set(["input","textarea","datalist","select"]),Ja=new Set(["canvas","body","html"]);function L(b){b.target.tagName&&Ja.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ka(b){b.target.tagName&&b.target.classList.contains("c3htmlwrap")&&b.preventDefault()}function La(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await K(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Ga(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Ma=!1;document.addEventListener("pause",()=>Ma=!0);document.addEventListener("resume",()=>Ma=!1);function va(b){b.addEventListener("selectstart",L);b.addEventListener("gesturehold",L);b.addEventListener("pointerdown",L)}function wa(b){b.addEventListener("selectstart",Ka);b.addEventListener("gesturehold",Ka);b.addEventListener("touchstart",Ka)}function xa(b){b.Vd=!0;b.fd=b.j.ra();b.Ab=b.j.ia()}
function H(b){if(!b.ma){var a=I.nb();a&&"any"!==b.pd&&Na(b);m(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.ra(),innerHeight:b.ia()})}}async function Oa(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Pa(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Qa(b){return await self.C3_GetSvgImageSize(b.blob)}function Ra(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Sa(b){self.setTimeout(()=>{b.Ud=!0},1E3);"cordova"===b.j.u?(document.addEventListener("pause",()=>Ta(b,!0)),document.addEventListener("resume",()=>Ta(b,!1))):document.addEventListener("visibilitychange",()=>Ta(b,"hidden"===document.visibilityState));b.hc=!("hidden"!==document.visibilityState&&!Ma);return{isSuspended:b.hc}}
function Ua(b){b.Qd||(b.Qd=!0,window.addEventListener("deviceorientation",a=>{b.ma||m(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},J)}),window.addEventListener("deviceorientationabsolute",a=>{b.ma||m(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},J)}))}
function Va(b){b.Pd||(b.Pd=!0,window.addEventListener("devicemotion",a=>{if(!b.ma){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});m(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},J)}}))}async function Wa(b){await Da(b.url)}
function Xa(b,a){b.Xd=a.message;-1===b.Vc&&(b.Vc=setTimeout(()=>{b.Vc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Xd)},250))}function Ya(b,a){console.warn("[Construct] Fullscreen request failed: ",a);m(b,"fullscreenerror",{isFullscreen:I.nb(),innerWidth:b.ra(),innerHeight:b.ia()})}
function Ta(b,a){b.hc!==a&&((b.hc=a)?b.j.Gc():b.j.Pc(),m(b,"visibilitychange",{hidden:a}),!a&&b.j.ob()&&(b=()=>{document.scrollingElement.scrollTop=0;document.scrollingElement.scrollLeft=0},setTimeout(b,50),setTimeout(b,100),setTimeout(b,250),setTimeout(b,500)))}
function Za(b,a,c){"Backspace"===c.key&&L(c);if(b.j.qa()){var d=["r","p","f","g","u"];(["F3","F5","F7"].includes(c.key)||c.ctrlKey&&d.includes(c.key))&&c.preventDefault()}b.ma||(d=Aa.get(c.code)||c.code,n(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},J))}
function M(b,a,c,d){b.ma||c.sourceCapabilities&&c.sourceCapabilities.firesTouchEvents||c.originalEvent&&c.originalEvent.sourceCapabilities&&c.originalEvent.sourceCapabilities.firesTouchEvents||n(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.Fa,pageX:c.pageX,pageY:c.pageY+b.Fa,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}
function N(b,a,c){if(!b.ma){var d=0;"mouse"===c.pointerType&&(d=b.hd);n(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.Fa,pageX:c.pageX,pageY:c.pageY+b.Fa,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},J);"mouse"===c.pointerType&&
(b.hd=c.buttons)}}function $a(b,a,c){document.body.style.position="";document.body.style.overflow="";document.body.style.transform="";b.Fa=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.position="absolute",document.body.style.overflow="visible",document.body.style.transform=`translateY(${-a}px)`,b.Fa=a))}}
function ab(b,a,c,d){const e=b.ra(),f=b.ia();b.fb=-1;e!=a||f!=c?m(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:I.nb()}):10>d&&bb(b,e,f,d+1)}function bb(b,a,c,d){-1!==b.fb&&clearTimeout(b.fb);b.fb=setTimeout(()=>ab(b,a,c,d),48)}
function Na(b){b=b.pd;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function cb(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
I.ib(class extends self.kb{constructor(b){super(b,"runtime");this.Vd=!1;this.fb=-1;this.pd="any";this.hc=this.Pd=this.Qd=!1;this.nc=document.createElement("div");this.nc.className="c3-screen-reader-text";this.nc.setAttribute("aria-live","polite");document.body.appendChild(this.nc);this.Na=null;this.ma=!1;this.Xd="";this.Vc=-1;this.Ud=!1;this.fd=b.ra();this.Ab=b.ia();this.Fa=this.Kb=0;b.B("runtime","invoke-download",c=>{const d=c.url;c=c.filename;const e=document.createElement("a"),f=document.body;
e.textContent=c;e.href=d;e.download=c;f.appendChild(e);e.click();f.removeChild(e)});b.B("runtime","load-webfonts",c=>Oa(c));b.B("runtime","raster-svg-image",c=>Pa(c));b.B("runtime","get-svg-image-size",c=>Qa(c));b.B("runtime","set-target-orientation",c=>{this.pd=c.targetOrientation});b.B("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.B("runtime","post-to-debugger",c=>Ra(c));b.B("runtime","go-to-script",c=>Ra(c));b.B("runtime","before-start-ticking",()=>Sa(this));b.B("runtime",
"debug-highlight",c=>{if(c.show){this.Na||(this.Na=document.createElement("div"),this.Na.id="inspectOutline",document.body.appendChild(this.Na));var d=this.Na;d.style.display="";d.style.left=c.left-1+"px";d.style.top=c.top-1+"px";d.style.width=c.width+2+"px";d.style.height=c.height+2+"px";d.textContent=c.name}else this.Na&&(this.Na.style.display="none")});b.B("runtime","enable-device-orientation",()=>Ua(this));b.B("runtime","enable-device-motion",()=>Va(this));b.B("runtime","add-stylesheet",c=>Wa(c));
b.B("runtime","script-create-worker",c=>{const d=c.port2;(new Worker(c.url,c.opts)).postMessage({type:"construct-worker-init",port2:d},[d])});b.B("runtime","alert",c=>this.Lc(c));b.B("runtime","screen-reader-text",c=>{var d=c.type;"create"===d?(d=document.createElement("p"),d.id="c3-sr-"+c.id,d.textContent=c.text,this.nc.appendChild(d)):"update"===d?(d=document.getElementById("c3-sr-"+c.id))?d.textContent=c.text:console.warn(`[Construct] Missing screen reader text with id ${c.id}`):"release"===d?
(d=document.getElementById("c3-sr-"+c.id))?d.remove():console.warn(`[Construct] Missing screen reader text with id ${c.id}`):console.warn(`[Construct] Unknown screen reader text update '${d}'`)});b.B("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.B("runtime","set-exporting-to-video",c=>{this.ma=!0;const d=document.createElement("h1");d.id="exportToVideoMessage";d.textContent=c.message;document.body.prepend(d);document.body.classList.add("exportingToVideo");
this.j.Je().style.display="";this.j.Qe(c.duration)});b.B("runtime","export-to-video-progress",c=>Xa(this,c));b.B("runtime","exported-to-video",c=>{window.yf({type:"exported-video",arrayBuffer:c.arrayBuffer,contentType:c.contentType,time:c.time})});b.B("runtime","exported-to-image-sequence",c=>{window.yf({type:"exported-image-sequence",blobArr:c.blobArr,time:c.time,gif:c.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const d=c.target;a.has(d.tagName.toLowerCase())||
Ha(d)||c.preventDefault()});window.addEventListener("selectstart",L);window.addEventListener("gesturehold",L);window.addEventListener("touchstart",L,{passive:!1});window.addEventListener("pointerdown",L,{passive:!1});this.hd=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",La,{passive:!1});window.addEventListener("wheel",La,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.ma&&this.Vd){var c=this.ra();var d=this.ia();if(this.j.Bc()){if(this.Ud){if(this.fd===
c&&d<this.Ab){this.Kb=this.Ab-d;$a(this,this.Ab,this.Kb);c=void 0;break a}0<this.Kb&&(this.Kb=0,$a(this,d,this.Kb))}this.fd=c;this.Ab=d}m(this,"window-resize",{innerWidth:c,innerHeight:d,devicePixelRatio:window.devicePixelRatio,isFullscreen:I.nb()});this.j.ob()&&(-1!==this.fb&&clearTimeout(this.fb),ab(this,c,d,0))}c=void 0}return c});window.addEventListener("fullscreenchange",()=>H(this));window.addEventListener("webkitfullscreenchange",()=>H(this));window.addEventListener("mozfullscreenchange",()=>
H(this));window.addEventListener("fullscreenerror",c=>Ya(this,c));window.addEventListener("webkitfullscreenerror",c=>Ya(this,c));window.addEventListener("mozfullscreenerror",c=>Ya(this,c));if(b.ob()){if(window.visualViewport){let c=Infinity;window.visualViewport.addEventListener("resize",()=>{const d=window.visualViewport.height;d>c&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0);c=d})}else window.addEventListener("focusout",()=>{{const e=document.activeElement;if(e){var c=
e.tagName.toLowerCase();var d=new Set("email number password search tel text url".split(" "));c="textarea"===c?!0:"input"===c?d.has(e.type.toLowerCase()||"text"):Ha(e)}else c=!1}c||(document.scrollingElement.scrollTop=0)});document.documentElement.setAttribute("ioswebview","")}this.Za=new Set;this.dc=new WeakSet;this.Ba=!1}wd(){window.addEventListener("focus",()=>{m(this,"window-focus",null,Ca)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=
!1}m(this,"window-blur",{parentHasFocus:a},Ca);this.hd=0});window.addEventListener("focusin",a=>{a=a.target;(Ia.has(a.tagName.toLowerCase())||Ha(a))&&m(this,"keyboard-blur",null,Ca)});window.addEventListener("keydown",a=>Za(this,"keydown",a));window.addEventListener("keyup",a=>Za(this,"keyup",a));window.addEventListener("mousedown",a=>M(this,"mousedown",a,Ba));window.addEventListener("mousemove",a=>M(this,"mousemove",a,Ba));window.addEventListener("mouseup",a=>M(this,"mouseup",a,Ba));window.addEventListener("dblclick",
a=>M(this,"dblclick",a,J));window.addEventListener("wheel",a=>{this.ma||m(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.Fa,pageX:a.pageX,pageY:a.pageY+this.Fa,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},J)});window.addEventListener("pointerdown",a=>{window!==window.top&&window.focus();cb(a.target)&&document.activeElement&&!cb(document.activeElement)&&document.activeElement.blur();N(this,"pointerdown",a)});this.j.ea&&"undefined"!==typeof window.onpointerrawupdate&&
self===self.top?window.addEventListener("pointerrawupdate",a=>{N(this,"pointermove",a)}):window.addEventListener("pointermove",a=>N(this,"pointermove",a));window.addEventListener("pointerup",a=>N(this,"pointerup",a));window.addEventListener("pointercancel",a=>N(this,"pointercancel",a));const b=()=>this.Oc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",
b,!0);this.j.Le()&&!this.j.Bc()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{$a(this,this.ia(),navigator.virtualKeyboard.boundingRect.height)}));this.j.ob()&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0)}ra(){return this.j.ra()}ia(){return this.j.ia()}Oc(){var b=[...this.Za];this.Za.clear();if(!this.Ba)for(const a of b)(b=a.play())&&b.catch(()=>{this.dc.has(a)||this.Za.add(a)})}ba(b){if("function"!==
typeof b.play)throw Error("missing play function");this.dc.delete(b);let a;try{a=b.play()}catch(c){this.Za.add(b);return}a&&a.catch(()=>{this.dc.has(b)||this.Za.add(b)})}ha(b){this.Za.delete(b);this.dc.add(b)}Qb(b){this.Ba=!!b}Lc(b){alert(b.message)}});"use strict";
async function ta(b){if(b.rf)throw Error("already initialised");b.rf=!0;var a=b.Da.Ic(("playable-ad"===b.Da.u?b.Da.eb:"")+"dispatchworker.js");b.Uc=await b.Da.uc(a,b.sb,{name:"DispatchWorker"});a=new MessageChannel;b.$c=a.port1;b.Uc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.kd=await za(b)}function ua(b){return[b.$c,b.kd]}
async function za(b){const a=b.ce.length;var c=b.Da.Ic(("playable-ad"===b.Da.u?b.Da.eb:"")+"jobworker.js");c=await b.Da.uc(c,b.sb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Uc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.ce.push(c);return e.port1}
self.Oe=class{constructor(b){this.Da=b;this.sb=b.aa;this.sb="preview"===b.u?this.sb+"workers/":this.sb+b.eb;this.tf=Math.min(navigator.hardwareConcurrency||2,16);this.Uc=null;this.ce=[];this.kd=this.$c=null}};"use strict";window.C3_Is_Supported&&(window.c3_runtimeInterface=new self.ya({Hf:!0,If:"workermain.js",gb:["scripts/c3runtime.js"],rc:[],ud:"",Ef:"scripts/",sc:[],re:"html5"}));"use strict";
async function db(b,a){a=a.type;let c=!0;0===a?c=await eb():1===a&&(c=await fb());m(b,"permission-result",{type:a,result:c})}async function eb(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function fb(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.ya.ib(class extends self.kb{constructor(b){super(b,"touch");q(this,"request-permission",a=>db(this,a))}});"use strict";const gb=180/Math.PI;
async function hb(b,a){if(a.isiOSCordova||a.isSafari)b.jc=!0;b.qd=a.timeScaleMode;b.he=["equalpower","HRTF","soundfield"][a.panningModel];b.Td=["linear","inverse","exponential"][a.distanceModel];b.ie=a.refDistance;b.ge=a.maxDistance;b.ke=a.rolloffFactor;if(b.j.ad)b.jc=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.j.Wd)});else{var c={latencyHint:a.latencyHint};b.ne||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");ib(b);b.g.onstatechange=()=>{"running"!==b.g.state&&ib(b);m(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Ua=b.g.createGain();b.Ua.connect(b.g.destination);c=a.listenerPos;b.$[0]=c[0];b.$[1]=c[1];b.$[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.ca);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>O(b,
d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function lb(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,k=a.vol,l=a.pos,p=a.panning,r=a.stereoPan;let t=a.off;0<t&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),t=t-a.performanceTime/1E3+a.contextTime):t=t-performance.now()/1E3+b.g.currentTime);b.de=g.slice(0);mb(b,g);try{b.R=await nb(b,c,d,e,g,f);if(p){P(b.R,!0);var u=b.R,C=p.innerAngle,pa=p.outerAngle,qa=p.outerGain;if(u.yb){ob(u,p.x,p.y,p.z,p.angle);var E=self.jb.Re;u.va[0]!==E(C)&&
(u.va[0]=E(C),u.F.coneInnerAngle=E(C));u.va[1]!==E(pa)&&(u.va[1]=E(pa),u.F.coneOuterAngle=E(pa));u.va[2]!==qa&&(u.va[2]=qa,u.F.coneOuterGain=qa)}p.hasOwnProperty("uid")&&(b.R.ta=p.uid)}else"number"===typeof r&&0!==r?(Q(b.R,!0),pb(b.R,r)):(P(b.R,!1),Q(b.R,!1));b.R.Play(h,k,l,t)}catch(Db){console.error("[Construct] Audio: error starting playback: ",Db);return}finally{c=g.join(" ");d=b.Gb.get(c);if(!d)throw Error("expected pending tag");d.vd--;0===d.vd&&(d.resolve(),b.Gb.delete(c))}w(b)}
async function qb(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await rb(b,c);for(const h of R(b,c))if(!h.Aa){c=h.G.gain;c.cancelScheduledValues(0);var f=h.v.g.currentTime,g=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,g);h.Qa=d;h.Xa=g;h.me=a}S(b)}async function sb(b,a){const c=a.tags;a=a.rate;await rb(b,c);for(const d of R(b,c))d.na!==a&&(d.na=a,d.Ka())}async function tb(b,a){const c=a.tags;a=a.pos;await rb(b,c);for(const d of R(b,c))d.Cc(a)}
async function ub(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await nb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function vb(b,a){if(a=await O(b,"",a.url,a.type,a.isMusic,!0))a.l(),a=b.ka.indexOf(a),-1!==a&&b.ka.splice(a,1)}
async function wb(b,a){const c=a.type;var d=a.hasOwnProperty("tags")?a.tags:[a.tag];const e=a.params;let f;if("convolution"===c)try{f=await O(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(k){console.log("[Construct] Audio: error loading convolution: ",k);return}for(const k of d){if("filter"===c)d=new self.xe(b,...e);else if("delay"===c)d=new self.ve(b,...e);else if("convolution"===c){var g=d=new self.ue(b,f.ja,...e),h=a.bufferType;g.Rd=a.bufferOriginalUrl;g.Sd=h}else if("flanger"===c)d=
new self.ye(b,...e);else if("phaser"===c)d=new self.Ae(b,...e);else if("gain"===c)d=new self.ze(b,...e);else if("stereopan"===c)d=new self.Ce(b,...e);else if("tremolo"===c)d=new self.De(b,...e);else if("ringmod"===c)d=new self.Be(b,...e);else if("distortion"===c)d=new self.we(b,...e);else if("compressor"===c)d=new self.te(b,...e);else if("analyser"===c)d=new self.se(b,...e);else throw Error("invalid effect type");g=b;h=k;h=h.toLowerCase();let l=g.la.get(h);l||(l=[],g.la.set(h,l));d.ae=l.length;d.od=
h;l.push(d);xb(g,h)}yb(b)}
async function zb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.H)e.Ga()&&1===c||!e.Ga()&&2===c?d.push(e):e.l();b.H=d}for(const f of b.la.values())for(const g of f)g.l();b.la.clear();b.pc=a.timeScale;b.Wc=a.gameTime;d=a.listenerPos;b.$[0]=d[0];b.$[1]=d[1];b.$[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.ca[e]=d[e];b.g.listener.setOrientation(...b.ca)}b.Ba=a.isSilent;b.j.Qb(b.Ba);b.cc=a.masterVolume;b.Ua.gain.value=
b.cc;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>wb(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>Ab(b,f,c)));S(b)}
async function Bb(b,a){try{const c=b.g.suspend(a.time);b.$d?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.j.qb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>Cb(d)),b.$d=!0);await c}catch(c){Cb(c)}}
function ib(b){b.Xb||(b.Zc=!1,window.addEventListener("pointerup",b.Ea,!0),window.addEventListener("touchend",b.Ea,!0),window.addEventListener("click",b.Ea,!0),window.addEventListener("keydown",b.Ea,!0),b.Xb=!0)}
async function O(b,a,c,d,e,f){for(var g of b.ka)if(g.mb()===c)return await Eb(g),g;if(f)return null;if(e&&(b.jc||b.Zd)){f=0;for(let h=0,k=b.ka.length;h<k;++h)g=b.ka[h],b.ka[f]=g,g.Ga()?g.l():++f;b.ka.length=f}f="audio/webm; codecs=opus"===d&&!b.ne;e&&f&&(b.Zd=!0);c=!e||b.jc||f?new self.Ge(b,a,c,d,e,f):new self.Ee(b,a,c,d,e);b.ka.push(c);await Eb(c);b.fe.has(a)||(m(b,"buffer-metadata",{originalUrl:a,duration:c.ga()}),b.fe.add(a));return c}
function Fb(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function Gb(b,a){return(a=b.la.get(a.toLowerCase()))?a[0].N():b.fa()}function xb(b,a){a=a.toLowerCase();let c=b.fa();var d=b.la.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.fa()):e.U(d[f+1].N())}}for(const f of Hb(b,a))d=c,e=f.da||f.F||f.G,e.disconnect(),e.connect(d);b.Oa&&b.gd===a&&(b.Oa.disconnect(),b.Oa.connect(c))}
function*Hb(b,a){if(a)for(const c of b.H)Fb(0<c.pa.length?c.pa[0]:"",a)&&(yield c);else b.R&&!b.R.O()&&(yield b.R)}function Ib(b,a,c){return c?b.j.qf(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Jb(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.P===a?f.l():++c}b.H.length=c}
function*R(b,a){if(0<a.length)for(const d of b.H){a:{b=d.pa;var c=a;for(const e of c){c=!1;for(const f of b)if(Fb(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.R&&!b.R.O()&&(yield b.R)}async function nb(b,a,c,d,e,f){for(const g of b.H)if(g.mb()===c&&(g.tc()||f))return g.pa=e,g;a=await O(b,a,c,d,f);e="html5"===a.Rc?new self.Fe(a.v,a,e):new self.He(a.v,a,e);b.H.push(e);return e}
function mb(b,a){a=a.join(" ");let c=b.Gb.get(a);if(!c){let d=null;c={vd:0,promise:new Promise(e=>d=e),resolve:d};b.Gb.set(a,c)}c.vd++}function rb(b,a){return(b=b.Gb.get((0===a.length?b.de:a).join(" ")))?b.promise:Promise.resolve()}function S(b){if(0<b.Ta.size)w(b);else for(const a of b.H)if(!a.I&&!a.O()){w(b);break}}function Kb(b,a,c,d){m(b,"trigger",{type:a,tags:c,aiid:d})}function yb(b){b.bd||(b.bd=!0,Promise.resolve().then(()=>Lb(b)))}
function Lb(b){const a={};for(const [c,d]of b.la)a[c]=d.map(e=>e.lb());m(b,"fxstate",{fxstate:a});b.bd=!1}
async function Ab(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,k=a.isLooping,l=a.volume,p=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await nb(b,d,e,f,h,g)}catch(r){console.error("[Construct] Audio: error loading audio state: ",r);return}b=c;(d=a.pan)?(P(b,!0),e=b.F,f=d.pos,b.ab[0]=f[0],b.ab[1]=f[1],b.ab[2]=f[2],f=d.orient,b.$a[0]=f[0],b.$a[1]=f[1],b.$a[2]=f[2],e.setPosition(...b.ab),e.setOrientation(...b.$a),b.va[0]=d.cia,b.va[1]=d.coa,b.va[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.ta=d.uid):P(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?Q(b,!1):(Q(b,!0),pb(b,d));c.Play(k,l,p,0);a.isPlaying||c.pb();c.Kc(a)}}}function Cb(b){console.error("[Audio] Offline rendering error: ",b)}
self.jb=class extends self.kb{constructor(b){super(b,"audio");this.Ua=this.g=null;this.Xb=this.Zc=!1;this.Ea=()=>{if(!this.Zc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Xb&&(this.Zc=!0,window.removeEventListener("pointerup",this.Ea,!0),window.removeEventListener("touchend",this.Ea,!0),window.removeEventListener("click",this.Ea,!0),window.removeEventListener("keydown",
this.Ea,!0),this.Xb=!1)}};this.ka=[];this.H=[];this.R=null;this.de=[];this.fe=new Set;this.ee=-1;this.Gb=new Map;this.cc=1;this.Ba=!1;this.qd=0;this.pc=1;this.Wc=0;this.he="HRTF";this.Td="inverse";this.ie=600;this.ge=1E4;this.ke=1;this.$=[0,0,0];this.ca=[0,0,-1,0,1,0];this.Zd=this.jc=!1;this.ne=this.j.Me();this.la=new Map;this.Ta=new Set;this.$d=this.bd=!1;this.gd="";this.Oa=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Oa&&this.Oa.disconnect();this.gd=c.toLowerCase();this.Oa=this.g.createMediaStreamSource(a);
this.Oa.connect(Gb(this,this.gd))};this.Wb=null;self.C3Audio_GetOutputStream=()=>{this.Wb||(this.Wb=this.g.createMediaStreamDestination(),this.Ua.connect(this.Wb));return this.Wb.stream};self.C3Audio_DOMInterface=this;v(this,[["create-audio-context",a=>hb(this,a)],["play",a=>lb(this,a)],["stop",a=>{a=a.tags;for(const c of R(this,a))c.Ha()}],["stop-all",()=>{for(const a of this.H)a.Ha()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of R(this,c))a?d.pb():d.Pb();S(this)}],["set-volume",a=>
{const c=a.tags;a=a.vol;for(const d of R(this,c))T(d,a)}],["fade-volume",a=>qb(this,a)],["set-master-volume",a=>{this.cc=a.vol;this.Ua.gain.value=this.cc}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of R(this,c))Mb(d,a)}],["set-silent",a=>{this.Ba=a.isSilent;this.j.Qb(this.Ba);for(const c of this.H)c.Ub()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of R(this,c))d.Dc(a)}],["set-playback-rate",a=>sb(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of R(this,
c))Q(d,!0),pb(d,a)}],["seek",a=>tb(this,a)],["preload",a=>ub(this,a)],["unload",a=>vb(this,a)],["unload-all",()=>{for(const a of this.ka)a.l();this.ka.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.Ec(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>wb(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.la.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].Z(e,
f,g,a);yb(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.la.get(a);if(!d||!d.length)break;for(const e of d)e.l();this.la.delete(a);xb(this,a)}}],["tick",a=>{this.pc=a.timeScale;this.Wc=a.gameTime;this.ee=a.tickCount;if(0!==this.qd)for(var c of this.H)c.Ka();!(c=a.listenerPos)||this.$[0]===c[0]&&this.$[1]===c[1]&&this.$[2]===c[2]||(this.$[0]=c[0],this.$[1]=c[1],this.$[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.ca[0]!==
c[0]||this.ca[1]!==c[1]||this.ca[2]!==c[2]||this.ca[3]!==c[3]||this.ca[4]!==c[4]||this.ca[5]!==c[5])){for(let d=0;6>d;++d)this.ca[d]=c[d];this.g.listener.setOrientation(...this.ca)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.ta===a&&ob(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>zb(this,a)],["offline-render-audio",a=>Bb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}fa(){return this.Ua}GetAudioContextExtern(){return this.V()}GetDestinationNodeExtern(){return this.fa()}Ob(){return this.Ba}ba(b){this.j.ba(b)}ha(b){this.j.ha(b)}Ia(){for(var b of this.Ta)b.Ia();
b=this.g.currentTime;for(var a of this.H)a.Ia(b);a=this.H.filter(c=>!c.I&&!c.O()).map(c=>c.lb());m(this,"state",{tickCount:this.ee,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Ta].map(c=>({tag:c.od,index:c.ae,peak:c.bb,rms:c.je,binCount:c.m.frequencyBinCount,freqBins:c.Yd}))});0===a.length&&0===this.Ta.size&&aa(this)}static Re(b){return b*gb}static Bd(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static Pe(b){return Math.log(Math.max(Math.min(b,1),0))/Math.log(10)*
20}};self.ya.ib(self.jb);"use strict";function Eb(b){b.ac||(b.ac=b.Jc());return b.ac}self.xd=class{constructor(b,a,c,d,e){this.v=b;this.vf=a;this.Pa=c;this.T=d;this.sf=e;this.Rc="";this.ac=null}l(){this.ac=this.v=null}Jc(){}V(){return this.v.V()}yc(){return this.vf}mb(){return this.Pa}xc(){return this.T}Ga(){return this.sf}ga(){}};"use strict";
self.Ee=class extends self.xd{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Rc="html5";this.L=new Audio;this.L.crossOrigin="anonymous";this.L.autoplay=!1;this.L.preload="auto";this.Bb=this.Cb=null;this.L.addEventListener("canplaythrough",()=>!0);this.Fb=this.V().createGain();this.Eb=null;this.L.addEventListener("canplay",()=>{this.Cb&&(this.Cb(),this.Bb=this.Cb=null);!this.Eb&&this.L&&(this.Eb=this.V().createMediaElementSource(this.L),this.Eb.connect(this.Fb))});this.onended=null;this.L.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.L.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Pa}' error: `,f);this.Bb&&(this.Bb(f),this.Bb=this.Cb=null)})}l(){Jb(this.v,this);this.Fb.disconnect();this.Fb=null;this.Eb.disconnect();this.Eb=null;this.L&&!this.L.paused&&this.L.pause();this.L=this.onended=null;super.l()}Jc(){return new Promise((b,a)=>{this.Cb=b;this.Bb=a;this.L.src=this.Pa})}W(){return this.L}ga(){return this.L.duration}};"use strict";
async function Nb(b){if(b.La)return b.La;var a=b.v.j;if("cordova"===a.u&&a.Dd(b.Pa)&&a.Zb)b.La=await a.Mb(b.Pa);else{a=await fetch(b.Pa);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.La=await a.arrayBuffer()}}async function Ob(b){if(b.ja)return b.ja;b.ja=await Ib(b.v,b.La,b.uf);b.La=null}
self.Ge=class extends self.xd{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Rc="webaudio";this.ja=this.La=null;this.uf=!!f}l(){Jb(this.v,this);this.ja=this.La=null;super.l()}async Jc(){try{await Nb(this),await Ob(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Pa}': `,b)}}ga(){return this.ja?this.ja.duration:0}};"use strict";let Pb=0;
function P(b,a){a=!!a;b.yb!==a&&(b.yb=a,b.yb?(Q(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.v.he,b.F.distanceModel=b.v.Td,b.F.refDistance=b.v.ie,b.F.maxDistance=b.v.ge,b.F.rolloffFactor=b.v.ke),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.fa())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.fa())))}
function Q(b,a){a=!!a;b.$b!==a&&(b.$b=a,b.$b?(P(b,!1),b.da=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.da),b.da.connect(b.fa())):(b.da.disconnect(),b.da=null,b.G.disconnect(),b.G.connect(b.fa())))}function pb(b,a){b.$b&&b.nd!==a&&(b.da.pan.value=a,b.nd=a)}function T(b,a){b.Qa=a;b.G.gain.cancelScheduledValues(0);b.Xa=-1;b.G.gain.value=b.zc()}function Mb(b,a){a=!!a;b.Aa!==a&&(b.Aa=a,b.Ub())}
function ob(b,a,c,d,e){if(b.yb){var f=b.ab,g=b.$a,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function U(b){return b.dd?b.v.Wc:performance.now()/1E3}
self.yd=class{constructor(b,a,c){this.v=b;this.P=a;this.pa=c;this.Vb=Pb++;this.G=this.V().createGain();this.G.connect(this.fa());this.F=null;this.yb=!1;this.ab=[0,0,0];this.$a=[0,0,0];this.va=[0,0,0];this.da=null;this.$b=!1;this.nd=0;this.I=!0;this.Y=this.wa=this.J=!1;this.Qa=1;this.Aa=!1;this.na=1;b=this.v.qd;this.dd=1===b&&!this.Ga()||2===b;this.Xa=this.ta=-1;this.me=!1}l(){this.P=this.v=null;this.F&&(this.F.disconnect(),this.F=null);this.da&&(this.da.disconnect(),this.da=null);this.G.disconnect();
this.G=null}V(){return this.v.V()}fa(){return Gb(this.v,0<this.pa.length?this.pa[0]:"")}yc(){return this.P.yc()}mb(){return this.P.mb()}xc(){return this.P.xc()}Ga(){return this.P.Ga()}O(){}tc(){}IsPlaying(){return!this.I&&!this.J&&!this.O()}Ra(){}ga(){return this.P.ga()}Play(){}Ha(){}pb(){}Pb(){}Ia(b){-1!==this.Xa&&b>=this.Xa&&(this.Xa=-1,this.me&&this.Ha(),Kb(this.v,"fade-ended",this.pa,this.Vb))}zc(){const b=this.Qa;return isFinite(b)?b:0}Ob(){return this.v.Ob()}Ub(){}Dc(){}Ka(){}Cc(){}Ec(){}Ac(){}lb(){var b=
this.Vb,a=this.pa,c=this.ga(),d=-1===this.Xa?this.Qa:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.ab,orient:this.$a,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.ta}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Ra(),playbackRate:this.na,uid:this.ta,bufferOriginalUrl:this.yc(),bufferUrl:"",bufferType:this.xc(),isMusic:this.Ga(),isLooping:this.Y,isMuted:this.Aa,resumePosition:this.Ac(),pan:f,stereoPan:this.da?
this.nd:null}}Kc(b){var a=b.playbackRate;this.na!==a&&(this.na=a,this.Ka());Mb(this,b.isMuted)}};"use strict";
self.Fe=class extends self.yd{constructor(b,a,c){super(b,a,c);this.P.Fb.connect(this.G);this.P.onended=()=>this.Mc()}l(){this.Ha();this.P.Fb.disconnect();super.l()}W(){return this.P.W()}Mc(){this.I=!0;this.ta=-1;Kb(this.v,"ended",this.pa,this.Vb)}O(){return this.W().ended}tc(){return this.I?!0:this.O()}Ra(){let b=this.W().currentTime;this.Y||(b=Math.min(b,this.ga()));return b}Play(b,a,c){const d=this.W();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);T(this,a);this.Aa=!1;d.muted&&(d.muted=
!1);if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.mb()}' to position '${c}': `,e)}this.v.ba(d);this.J=this.I=!1;this.Y=b;this.na=1}Ha(){const b=this.W();b.paused||b.pause();this.v.ha(b);this.I=!0;this.J=!1;this.ta=-1}pb(){if(!(this.J||this.I||this.O())){var b=this.W();b.paused||b.pause();this.v.ha(b);this.J=!0}}Pb(){!this.J||this.I||this.O()||(this.v.ba(this.W()),this.J=!1)}Ub(){this.W().muted=this.Aa||this.Ob()}Dc(b){b=!!b;this.Y!==
b&&(this.Y=b,this.W().loop=b)}Ka(){let b=this.na;this.dd&&(b*=this.v.pc);try{this.W().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}Cc(b){if(!this.I&&!this.O())try{this.W().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}Ac(){return this.Ra()}Ec(b){b?this.IsPlaying()?(this.W().pause(),this.wa=!0):this.wa=!1:this.wa&&(this.v.ba(this.W()),this.wa=!1)}};"use strict";
function V(b){b.s&&(b.s.onended=null,b.s.disconnect(),b.s.buffer=null);b.s=null;b.rb=null}
self.He=class extends self.yd{constructor(b,a,c){super(b,a,c);this.s=null;this.fc=d=>this.Mc(d);this.Yc=!0;this.rb=null;this.S=this.ic=this.kc=0;this.jd=1}l(){this.Ha();V(this);this.fc=null;super.l()}Mc(b){this.J||this.wa||b.target!==this.rb||(this.I=this.Yc=!0,this.ta=-1,V(this),Kb(this.v,"ended",this.pa,this.Vb))}O(){return!this.I&&this.s&&this.s.loop||this.J?!1:this.Yc}tc(){return!this.s||this.I?!0:this.O()}Ra(){let b;b=this.J?this.S:this.ic+(U(this)-this.kc)*this.na;this.Y||(b=Math.min(b,this.ga()));
return b}Play(b,a,c,d){this.Aa=!1;this.jd=1;T(this,a);V(this);this.s=this.V().createBufferSource();this.s.buffer=this.P.ja;this.s.connect(this.G);this.rb=this.s;this.s.onended=this.fc;this.s.loop=b;this.s.start(d,c);this.J=this.I=this.Yc=!1;this.Y=b;this.na=1;this.kc=U(this);this.ic=c}Ha(){if(this.s)try{this.s.stop(0)}catch(b){}this.I=!0;this.J=!1;this.ta=-1}pb(){this.J||this.I||this.O()||(this.S=this.Ra(),this.Y&&(this.S%=this.ga()),this.J=!0,this.s.stop(0))}Pb(){!this.J||this.I||this.O()||(V(this),
this.s=this.V().createBufferSource(),this.s.buffer=this.P.ja,this.s.connect(this.G),this.rb=this.s,this.s.onended=this.fc,this.s.loop=this.Y,T(this,this.Qa),this.Ka(),this.s.start(0,this.S),this.kc=U(this),this.ic=this.S,this.J=!1)}zc(){return super.zc()*this.jd}Ub(){this.jd=this.Aa||this.Ob()?0:1;T(this,this.Qa)}Dc(b){b=!!b;this.Y!==b&&(this.Y=b,this.s&&(this.s.loop=b))}Ka(){let b=this.na;this.dd&&(b*=this.v.pc);this.s&&(this.s.playbackRate.value=b)}Cc(b){this.I||this.O()||(this.J?this.S=b:(this.pb(),
this.S=b,this.Pb()))}Ac(){return this.S}Ec(b){b?this.IsPlaying()?(this.wa=!0,this.S=this.Ra(),this.Y&&(this.S%=this.ga()),this.s.stop(0)):this.wa=!1:this.wa&&(V(this),this.s=this.V().createBufferSource(),this.s.buffer=this.P.ja,this.s.connect(this.G),this.rb=this.s,this.s.onended=this.fc,this.s.loop=this.Y,T(this,this.Qa),this.Ka(),this.s.start(0,this.S),this.kc=U(this),this.ic=this.S,this.wa=!1)}Kc(b){super.Kc(b);this.S=b.resumePosition}};"use strict";function W(b){return b.g.createGain()}
function X(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Y{constructor(b){this.v=b;this.g=b.V();this.ae=-1;this.T=this.od="";this.o=null}l(){this.g=null}N(){}U(){}lb(){return{type:this.T,tag:this.od,params:this.o}}}
self.xe=class extends Y{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.o=[a,c,d,e,f,g];this.A=W(this);this.i=W(this);this.i.gain.value=g;this.h=W(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i)}l(){this.A.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.l()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 1:this.o[1]=a;X(this,this.D.frequency,a,c,d);break;case 2:this.o[2]=a;X(this,this.D.detune,a,c,d);break;case 3:this.o[3]=a;X(this,this.D.Q,a,c,d);break;case 4:this.o[4]=a,X(this,this.D.gain,a,c,d)}}};
self.ve=class extends Y{constructor(b,a,c,d){super(b);this.T="delay";this.o=[a,c,d];this.A=W(this);this.i=W(this);this.i.gain.value=d;this.h=W(this);this.h.gain.value=1-d;this.Db=W(this);this.X=this.g.createDelay(a);this.X.delayTime.value=a;this.vb=W(this);this.vb.gain.value=c;this.A.connect(this.Db);this.A.connect(this.h);this.Db.connect(this.i);this.Db.connect(this.X);this.X.connect(this.vb);this.vb.connect(this.Db)}l(){this.A.disconnect();this.i.disconnect();this.h.disconnect();this.Db.disconnect();
this.X.disconnect();this.vb.disconnect();super.l()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){const e=self.jb.Bd;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[2]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 4:this.o[1]=e(a);X(this,this.vb.gain,e(a),c,d);break;case 5:this.o[0]=a,X(this,this.X.delayTime,a,c,d)}}};
self.ue=class extends Y{constructor(b,a,c,d){super(b);this.T="convolution";this.o=[c,d];this.Sd=this.Rd="";this.A=W(this);this.i=W(this);this.i.gain.value=d;this.h=W(this);this.h.gain.value=1-d;this.ub=this.g.createConvolver();this.ub.normalize=c;this.ub.buffer=a;this.A.connect(this.ub);this.A.connect(this.h);this.ub.connect(this.i)}l(){this.A.disconnect();this.ub.disconnect();this.i.disconnect();this.h.disconnect();super.l()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[1]=a,X(this,this.i.gain,a,c,d),X(this,this.h.gain,1-a,c,d)}}lb(){const b=super.lb();b.bufferOriginalUrl=this.Rd;b.bufferUrl="";b.bufferType=this.Sd;return b}};
self.ye=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.o=[a,c,d,e,f];this.A=W(this);this.h=W(this);this.h.gain.value=1-f/2;this.i=W(this);this.i.gain.value=f/2;this.wb=W(this);this.wb.gain.value=e;this.X=this.g.createDelay(a+c);this.X.delayTime.value=a;this.C=this.g.createOscillator();this.C.frequency.value=d;this.K=W(this);this.K.gain.value=c;this.A.connect(this.X);this.A.connect(this.h);this.X.connect(this.i);this.X.connect(this.wb);this.wb.connect(this.X);this.C.connect(this.K);
this.K.connect(this.X.delayTime);this.C.start(0)}l(){this.C.stop(0);this.A.disconnect();this.X.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();this.wb.disconnect();super.l()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[4]=a;X(this,this.i.gain,a/2,c,d);X(this,this.h.gain,1-a/2,c,d);break;case 6:this.o[1]=a/1E3;X(this,this.K.gain,a/1E3,
c,d);break;case 7:this.o[2]=a;X(this,this.C.frequency,a,c,d);break;case 8:this.o[3]=a/100,X(this,this.wb.gain,a/100,c,d)}}};
self.Ae=class extends Y{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.o=[a,c,d,e,f,g];this.A=W(this);this.h=W(this);this.h.gain.value=1-g/2;this.i=W(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.C=this.g.createOscillator();this.C.frequency.value=f;this.K=W(this);this.K.gain.value=e;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i);this.C.connect(this.K);this.K.connect(this.D.frequency);
this.C.start(0)}l(){this.C.stop(0);this.A.disconnect();this.D.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();super.l()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;X(this,this.i.gain,a/2,c,d);X(this,this.h.gain,1-a/2,c,d);break;case 1:this.o[0]=a;X(this,this.D.frequency,a,c,d);break;case 2:this.o[1]=a;X(this,this.D.detune,a,c,d);
break;case 3:this.o[2]=a;X(this,this.D.Q,a,c,d);break;case 6:this.o[3]=a;X(this,this.K.gain,a,c,d);break;case 7:this.o[4]=a,X(this,this.C.frequency,a,c,d)}}};self.ze=class extends Y{constructor(b,a){super(b);this.T="gain";this.o=[a];this.m=W(this);this.m.gain.value=a}l(){this.m.disconnect();super.l()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(b,a,c,d){const e=self.jb.Bd;switch(b){case 4:this.o[0]=e(a),X(this,this.m.gain,e(a),c,d)}}};
self.Ce=class extends Y{constructor(b,a){super(b);this.T="stereopan";this.o=[a];this.m=this.g.createStereoPanner();this.m.pan.value=a}l(){this.m.disconnect();super.l()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.o[0]=a,X(this,this.m.pan,a,c,d)}}};
self.De=class extends Y{constructor(b,a,c){super(b);this.T="tremolo";this.o=[a,c];this.m=W(this);this.m.gain.value=1-c/2;this.C=this.g.createOscillator();this.C.frequency.value=a;this.K=W(this);this.K.gain.value=c/2;this.C.connect(this.K);this.K.connect(this.m.gain);this.C.start(0)}l(){this.C.stop(0);this.C.disconnect();this.K.disconnect();this.m.disconnect();super.l()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=
a;X(this,this.m.gain,1-a/2,c,d);X(this,this.K.gain,a/2,c,d);break;case 7:this.o[0]=a,X(this,this.C.frequency,a,c,d)}}};
self.Be=class extends Y{constructor(b,a,c){super(b);this.T="ringmod";this.o=[a,c];this.A=W(this);this.i=W(this);this.i.gain.value=c;this.h=W(this);this.h.gain.value=1-c;this.Jb=W(this);this.Jb.gain.value=0;this.C=this.g.createOscillator();this.C.frequency.value=a;this.C.connect(this.Jb.gain);this.C.start(0);this.A.connect(this.Jb);this.A.connect(this.h);this.Jb.connect(this.i)}l(){this.C.stop(0);this.C.disconnect();this.Jb.disconnect();this.A.disconnect();this.i.disconnect();this.h.disconnect();super.l()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 7:this.o[0]=a,X(this,this.C.frequency,a,c,d)}}};
self.we=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.o=[a,c,d,e,f];this.A=W(this);this.mc=W(this);this.lc=W(this);b=d;.01>b&&(b=.01);this.mc.gain.value=b;this.lc.gain.value=Math.pow(1/b,.6)*e;this.i=W(this);this.i.gain.value=f;this.h=W(this);this.h.gain.value=1-f;this.qc=this.g.createWaveShaper();this.Sc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Sc[32768+e]=f,this.Sc[32768-
e-1]=-f;this.qc.curve=this.Sc;this.A.connect(this.mc);this.A.connect(this.h);this.mc.connect(this.qc);this.qc.connect(this.lc);this.lc.connect(this.i)}l(){this.A.disconnect();this.mc.disconnect();this.qc.disconnect();this.lc.disconnect();this.i.disconnect();this.h.disconnect();super.l()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[4]=a,X(this,this.i.gain,a,c,d),X(this,this.h.gain,
1-a,c,d)}}};self.te=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.o=[a,c,d,e,f];this.m=this.g.createDynamicsCompressor();this.m.threshold.value=a;this.m.knee.value=c;this.m.ratio.value=d;this.m.attack.value=e;this.m.release.value=f}l(){this.m.disconnect();super.l()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(){}};
self.se=class extends Y{constructor(b,a,c){super(b);this.T="analyser";this.o=[a,c];this.m=this.g.createAnalyser();this.m.fftSize=a;this.m.smoothingTimeConstant=c;this.Yd=new Float32Array(this.m.frequencyBinCount);this.le=new Uint8Array(a);this.je=this.bb=0;b=this.v;b.Ta.add(this);S(b)}l(){this.v.Ta.delete(this);this.m.disconnect();super.l()}Ia(){this.m.getFloatFrequencyData(this.Yd);this.m.getByteTimeDomainData(this.le);const b=this.m.fftSize;let a=this.bb=0;for(var c=0;c<b;++c){let d=(this.le[c]-
128)/128;0>d&&(d=-d);this.bb<d&&(this.bb=d);a+=d*d}c=self.jb.Pe;this.bb=c(this.bb);this.je=c(Math.sqrt(a/b))}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(){}};"use strict";async function Qb(b,a){b.cd=a.isInWorker;a=document.createElement("video");b.oc=!!a.requestVideoFrameCallback&&!b.j.Bc();const c=!!self.createImageBitmap;b.Hb=b.cd||c;return{postImageBitmaps:b.Hb,supportedFormats:{"video/webm":!!a.canPlayType("video/webm"),"video/mp4":!!a.canPlayType("video/mp4")}}}
async function Rb(b,a){if(!b.Tc.has(a)){a.c3_rvfcId=a.requestVideoFrameCallback(()=>Rb(b,a));try{const c=a.c3_sequenceNumber++,d=await createImageBitmap(a);c>a.c3_lastFrameSequence&&(a.c3_imageBitmap=d,a.c3_lastFrameSequence=c)}catch(c){}}}function Z(b,a,c,d){b.Tc.has(a)||x(b,"playback-event",c,{type:d})}
self.ya.ib(class extends self.vc{constructor(b){super(b);this.Hb=this.oc=this.cd=this.Ma=!1;this.ec=this.xf=0;this.Tc=new WeakSet;q(this,"init",a=>Qb(this,a));y(this,"play",a=>{this.ba(a)});y(this,"pause",a=>{this.ha(a);a.pause()});y(this,"set-source",(a,c)=>{a.src=c.src;a.load()});y(this,"set-playback-time",(a,c)=>{try{a.currentTime=c.time}catch(d){console.error("[Video] Exception setting playback time: ",d)}});y(this,"set-playback-rate",(a,c)=>{try{a.playbackRate=c.rate}catch(d){console.error("[Video] Exception setting playback rate: ",
d)}});y(this,"set-looping",(a,c)=>{a.loop=c.isLooping});y(this,"set-muted",(a,c)=>{a.muted=c.isMuted});y(this,"set-volume",(a,c)=>{a.volume=c.volume});self.C3Video_GetElement=a=>z(this,a)}ba(b){this.j.ba(b);this.Hb&&this.oc&&-1===b.c3_rvfcId&&(b.c3_rvfcId=b.requestVideoFrameCallback(()=>Rb(this,b)))}ha(b){this.j.ha(b);this.Hb&&this.oc&&-1!==b.c3_rvfcId&&(b.cancelVideoFrameCallback(b.c3_rvfcId),b.c3_rvfcId=-1)}Ad(b,a){const c=document.createElement("video");c.crossOrigin="anonymous";c.playsInline=
!0;c.c3_imageBitmap=null;c.c3_rvfcId=-1;c.c3_sequenceNumber=0;c.c3_lastFrameSequence=-1;c.addEventListener("canplay",()=>Z(this,c,b,0));c.addEventListener("canplaythrough",()=>Z(this,c,b,1));c.addEventListener("ended",()=>Z(this,c,b,2));c.addEventListener("error",()=>Z(this,c,b,3));c.addEventListener("loadstart",()=>Z(this,c,b,4));c.addEventListener("playing",()=>Z(this,c,b,5));c.addEventListener("pause",()=>Z(this,c,b,6));c.addEventListener("stalled",()=>Z(this,c,b,7));const d=a.autoplay;0===d?(c.autoplay=
!1,c.preload="none"):1===d?(c.autoplay=!1,c.preload="auto"):c.autoplay=!0;a.src&&(c.src=a.src);2===d&&this.ba(c);this.ec++;w(this);return c}Gd(){}Cd(b){this.ha(b);b&&!b.paused&&!b.ended&&0<b.currentTime&&b.pause();b.src="";this.ec=Math.max(this.ec-1,0);0===this.ec&&aa(this);this.Tc.add(b)}Ia(){const b={},a={sequenceNumber:this.xf++,videoData:b},c=[],d=[];for(const [e,f]of this.za.entries()){const g=f.Wa,h={currentTime:g.currentTime,playbackRate:g.playbackRate,duration:g.duration,videoWidth:g.videoWidth,
videoHeight:g.videoHeight};if(this.Hb)if(this.oc){const k=g.c3_imageBitmap;g.c3_imageBitmap=null;(h.imageBitmap=k)&&c.push(k)}else d.push(createImageBitmap(g).then(k=>{h.imageBitmap=k;c.push(k)}).catch(()=>{h.imageBitmap=null}));b[e.toString()]=h}Promise.all(d).then(()=>{this.cd?m(this,"state",a,!1,c):n(this,"state",a)})}});"use strict";function Sb(){}function Tb(b){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>m(b,"sw-message",a.data))}
function Ub(b){b=b.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}
self.ya.ib(class extends self.kb{constructor(b){super(b,"browser");this.u="";v(this,[["get-initial-state",a=>{this.u=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>
Tb(this)],["alert",a=>this.Lc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Nc(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>Ub(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?
screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var c=a.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===c)window.history.forward();else if("reload"===c)location.reload();else if("url"===c){c=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,
"_system"):"preview"===a||this.j.qa()?window.open(c,"_blank"):this.Nf||(2===d?window.top.location=c:1===d?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,a))}],["request-fullscreen",a=>{if(this.j.qa()||"macos-wkwebview"===this.u)self.ya.Tb(!0),this.j.Ja({type:"set-fullscreen",fullscreen:!0});else{const c={navigationUI:"auto"};a=a.navUI;1===a?c.navigationUI="hide":2===
a&&(c.navigationUI="show");a=document.documentElement;let d;a.requestFullscreen?d=a.requestFullscreen(c):a.mozRequestFullScreen?d=a.mozRequestFullScreen(c):a.msRequestFullscreen?d=a.msRequestFullscreen(c):a.webkitRequestFullScreen&&(d="undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen());d instanceof Promise&&d.catch(Sb)}}],["exit-fullscreen",()=>{if(this.j.qa()||"macos-wkwebview"===this.u)self.ya.Tb(!1),this.j.Ja({type:"set-fullscreen",
fullscreen:!1});else{let a;document.exitFullscreen?a=document.exitFullscreen():document.mozCancelFullScreen?a=document.mozCancelFullScreen():document.msExitFullscreen?a=document.msExitFullscreen():document.webkitCancelFullScreen&&(a=document.webkitCancelFullScreen());a instanceof Promise&&a.catch(Sb)}}],["set-hash",a=>{location.hash=a.hash}],["set-document-css-style",a=>{const c=a.prop,d=a.value;var e=a.selector;a=a["is-all"];try{if(e)if(a)var f=Array.from(document.querySelectorAll(e));else{var g=
document.querySelector(e);f=g?[g]:[]}else f=[document.documentElement];e=f;for(const h of e)c.startsWith("--")?h.style.setProperty(c,d):h.style[c]=d}catch(h){console.warn("[Browser] Failed to set style: ",h)}}],["get-document-css-style",a=>{{const d=a.prop;a=a.selector;try{const e=document.querySelector(a);var c=e?{isOk:!0,result:window.getComputedStyle(e).getPropertyValue(d)}:{isOk:!1}}catch(e){console.warn("[Browser] Failed to get style: ",e),c={isOk:!1}}}return c}],["set-window-size",a=>{window.resizeTo(a.windowWidth,
a.windowHeight)}],["set-window-position",a=>{window.moveTo(a.windowX,a.windowY)}]]);window.addEventListener("online",()=>{m(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{m(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{m(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{m(this,"backbutton")})}Lc(b){alert(b.message)}Nc(b){b=b.isFocus;if("nwjs"===this.u){const a="nwjs"===this.u?nw.Window.get():
null;b?a.focus():a.blur()}else b?window.focus():window.blur()}});
